### ISSUE TITLE
Fix colors for events in calendar view

### ISSUE THREAD

**Issue by jorgemoralespou** [evmanhq/evman#10]
In calendar view, colors for events and customer events should be different colors:

![image](https://user-images.githubusercontent.com/78350/34488002-002345e6-efd7-11e7-899a-c9dda462fe67.png)
Not sure if this is specific to the osevg instance and colors can be customized in an admin like view or directly in the database.

Anyhow, this should be different colors. Customer events are:
- customer meeting
- remote customer meeting

**Comment by marekjelen** [comment]
Team -> Settings -> Event Types
