### ISSUE TITLE
Rank popular cities higher

### ISSUE THREAD

**Issue by mhausenblas** [evmanhq/evman#11]
When creating an event, one of the required fields is "City". Currently, when entering a name such as "New York" one is presented with a very long list of choices where the most likely choice would be "New York City" (being the most popular, biggest city, most likely to host an event). It would be awesome and improve the UX if popular/bigger cities would be ranked higher than less popular/smaller cities.

**Comment by picsoung** [comment]
That exactly what I felt too.

There is a nice library for that: [Algolia Places](https://community.algolia.com/places/)
free to use, and pretty easy to integrate

**Comment by marekjelen** [comment]
hi, @mhausenblas @picsoung, please check if it's better. 

(the data is still being imported, but Europe should already be there)

**Comment by mhausenblas** [comment]
Perfect, thanks @marekjelen! Works like a charm ;)
