### ISSUE TITLE
Too Many Redirects 

### ISSUE THREAD

**Issue by ani6gup** [evmanhq/evman#17]
Hello, 

I am trying to use evman with my team, it seems like a really useful tool! However, I am encountering a reoccurring problem along with another team member, @elliotwhitehead

After logging into Evman through my GitHub account, the following page shows: 

<img width="1269" alt="screen shot 2018-05-16 at 9 18 50 am" src="https://user-images.githubusercontent.com/5401992/40129919-6e289614-58ea-11e8-893e-ba75b7998c8f.png">

I have tried clearing my cookies and switching browsers, however the same shows each time. 

Would love any help!

**Comment by elliotwhitehead** [comment]
Yep, +1 on the issue here. 

FWIW, I recently had signed up using GitHub about two weeks ago, but currently not able to log in. I've tried Incognito / deleting cookies. Also, my user id is 627 if that helps.

Thanks in advance! 🙏

**Comment by marekjelen** [comment]
It should be solved now, please try again. Thanks

**Comment by elliotwhitehead** [comment]
It is fixed. Thanks so much!

**Comment by marekjelen** [comment]
Thanks for the feedback.
