### ISSUE TITLE
Redirecting to Profile View 

### ISSUE THREAD

**Issue by ani6gup** [evmanhq/evman#19]
👋 Hello there

I am still having some issues after the following [one](https://github.com/evmanhq/evman/issues/17) was resolved. It seems like my left sidebar is missing 'Events'. When I go to the calendar tab then click 'calendar' it redirects me to my profile page. 

My user is 626! 

Also here is a picture: 

<img width="1280" alt="screen shot 2018-05-22 at 10 28 27 am" src="https://user-images.githubusercontent.com/5401992/40379428-e84b7582-5daa-11e8-8d85-f2d80705ed91.png">

**Comment by marekjelen** [comment]
Hello, that means you are not a member of any team, yet. There is an icon of a group of people, where you can create your own team, or you need to ask someone who is already member of some team to invite you.

**Comment by ani6gup** [comment]
@marekjelen thank you! My team member has reinvited me, however when I click the link it goes back to my profile page which remains unchanged. I have tried 3 of the invite links so far.

**Comment by marekjelen** [comment]
can you join evman.slack.com?

**Comment by ani6gup** [comment]
Yes, would you be able to invite me through the email ani6gup@gmail.com?
