### ISSUE TITLE
Fulltext city search not working?

### ISSUE THREAD

**Issue by bastichelaar** [evmanhq/evman#21]
Hi guys, first of all, great product! We're trying to run it ourselves using Docker, and almost everything seems to work fine, except for the city search. It doesn't return any items with the fulltext search. When I browse to `/geo/cities.json`, I get a list of the cities, but it seems paginated. When I GET `/geo/cities.json?fulltext=Amsterdam` I don't get any results. When I do a GET on `/geo/cities.json?ids=98442`, it nicely returns Amsterdam. Am I missing something?

**Comment by bastichelaar** [comment]
Update: I deleted the created views/tables and did the migration manually. Everything is working now!

**Comment by DEGoodmanWilson** [comment]
Hi! I'm having the same problem, and I'm wondering what the right solution is. @bastichelaar could you help me understand the steps you took to resolve the issue?

**Comment by DEGoodmanWilson** [comment]
Ah, nevermind, sorted. Just needed to run
```sql
REFRESH MATERIALIZED VIEW cities_fulltext_view WITH DATA;
```
on the DB
